# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Use this GitHub Action
      # - name: get-npm-version
        # uses: martinbeentjes/npm-get-version-action@master
        # id: package-version

      - name: Setup NodeJS 14
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Configure AWS credentials
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Run NPM Install (Production)
        run: npm ci
        
      - name: Run NPM Build
        run: npm run build

      - name: Setup AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Sync output to S3
        run: aws s3 sync ./output/ s3://ccontrol-games/${GITHUB_REPOSITORY##*/} --delete --exclude=*.git/* --exclude=*.github/*
